name: Trimorph CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl sudo

      - name: Make scripts executable
        run: chmod +x ./usr/local/sbin/*

      - name: Run bats tests
        run: ./test/bats-core/bin/bats test/core.bats